---
- id: google-java-format
  name: Google Java Formatter
  description: "Runs the Google Java Formatter on Java source files."
  language: script
  entry: ./format-code.sh
  files: \.java$
  require_serial: true
